server:
  port: 9994
  servlet:
    context-path: /maya

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    # Postgres
    url: jdbc:postgresql://maya-server-001.swinfra.net:5432/maya
    username: postgres
    password: Admin_1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false

logging:
  level:
    root: info
    com.opentext.mayaserver: info
    org.springframework.web: info

  file:
    name: ${java.io.tmpdir}/mayaServerApplication.log
#springdoc:
#  api-docs:
#    path: /swagger-ui.html
#    resolve-schema-properties: off
maya-server:
  host: maya-server-001.swinfra.net
  byodDataPath: /mnt/byod
  s3Mock:
    nfs: /mnt/aws-bills
  mockoon:
    nfsDataPath: /var/opt
    nfsConfigPath: /mnt
  recommendation:
    nfsDataPath: ${java.io.tmpdir}
    nfsConfigPath: ${java.io.tmpdir}
  azurite:
    nfs: /mnt/azure-bills
